content: |-

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true

recursive:
  enabled: true
  path: ./modules